### ISSUE TITLE
Infografua

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Julissamigdalia#1]
[Infografia. Julissa Migdalia Jose Cruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Julissamigdalia/files/11084543/Infografia.Julissa.Migdalia.Jose.Cruz.pdf)

**Comment by Arlet04** [comment]
Partes de infografía: Faltaron referencias 3 
Coherencia:excelente 4 
Organización: Falta distribuir bien la información 3  
Diseño: Falta organizar mas el diseño 2 
Creatividad: falta implementar mas creatividad 3
Puntos:15/20
Calificación 15 / 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
